
image: daedalusproject/base_golang_1_13:latest

stages:
    - dep
    - test

before_script:
  - mkdir -p "$(pwd)/go"
  - go env -w GOPATH="$(pwd)/go"
  - mkdir -p $GOPATH/src/a-castellano
  - ln -s ${CI_PROJECT_DIR} $(pwd)/go/src/a-castellano/metal-archives-wrappe
  - cd $(pwd)/go/src/a-castellano/metal-archives-wrappe

unit_tests:
  stage: dep
  script:
    - make dep

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  script:
    - make lint
