
image: daedalusproject/base_golang_1_13:latest

stages:
    - dep
    - test

before_script:
  - export GOPATH="$(pwd)/go"
  - mkdir -p "$(pwd)/go"
  - go env -w GOPATH="$(pwd)/go"
  - mkdir -p $GOPATH/src/a-castellano
  - ln -s ${CI_PROJECT_DIR} $GOPATH/src/a-castellano/metal-archives-wrapper
  - cd $GOPATH/src/a-castellano/metal-archives-wrapper

dep:
  stage: dep
  script:
    - make dep
  artifacts:
    name: "vendor-$CI_PIPELINE_ID"
    paths:
      - vendor/
    expire_in: 1 hour

unit_tests:
  stage: test
  script:
    - pwd
    - make test

race_detector:
  stage: test
  script:
    - make race

memory_sanitizer:
  stage: test
  script:
    - make msan

code_coverage:
  stage: test
  script:
    - make coverage

code_coverage_report:
  stage: test
  script:
    - make coverhtml
  only:
  - master

lint_code:
  stage: test
  script:
    - make lint
